PrimeFaces.locales['bg'] = {
	closeText : '-',
	prevText : 'Предишен',
	nextText : 'Следващ',
	monthNames : [ 'Януари', 'Февруари', 'Март', 'Април', 'Май', 'Юни', 'Юли',
			'Август', 'Септември', 'Октомври', 'Ноември', 'Декември' ],
	monthNamesShort : [ 'Яну', 'Фев', 'Мар', 'Апр', 'Май', 'Юни', 'Юли', 'Явг',
			'Сеп', 'Окт', 'Ное', 'Дек' ],
	dayNames : [ 'Неделя', 'Понеделник', 'Вторник', 'Сряда', 'Четвъртък',
			'Петък', 'Събота' ],
	dayNamesShort : [ 'нд', 'пн', 'вт', 'ср', 'чт', 'пт', 'сб' ],
	dayNamesMin : [ 'Н', 'П', 'В', 'С ', 'Ч', 'П ', 'С' ],
	weekHeader : 'Седмица',
	firstDay : 1,
	isRTL : false,
	showMonthAfterYear : false,
	yearSuffix : '',
	timeOnlyTitle : 'Само време',
	timeText : 'Време',
	hourText : 'Час',
	minuteText : 'Минути',
	secondText : 'Секунди',
	currentText : 'Текуща дата',
	ampm : false,
	month : 'Месец',
	week : 'Седмица',
	day : 'Ден',
	allDayText : 'Всеки ден'
};